SELECT *
FROM courses;

DROP TABLE courses;

-- DEFAULT VALUES
CREATE TABLE courses (
    id INTEGER,
    course_name VARCHAR(40),
    price NUMERIC(6,2) DEFAULT 0
);

INSERT INTO courses (id, course_name) VALUES
(1, 'JAVA 1');

SELECT * FROM courses;

ALTER TABLE courses
ALTER COLUMN price SET DEFAULT 199.99;

INSERT INTO courses (id, course_name) VALUES
(2, 'JAVA 2');

ALTER TABLE courses
ALTER COLUMN price DROP DEFAULT;

INSERT INTO courses (id, course_name) VALUES
(3, 'JAVA 3');

SELECT * FROM courses;


-- PRIMARY KEY
CREATE TABLE games(
    id INTEGER,
    game_name VARCHAR(50),
    release_date DATE,

    CONSTRAINT id_pk PRIMARY KEY (id)
);

DROP TABLE games;

CREATE TABLE games(
    id INTEGER PRIMARY KEY,
    game_name VARCHAR(50),
    release_date DATE
);

ALTER TABLE games
ADD CONSTRAINT games_pk primary key(id);

INSERT INTO games
VALUES (1, 'Dark Souls 1', '2011-09-22');

INSERT INTO games
VALUES (2, 'Dark Souls 2', '2014-03-1');

INSERT INTO games
VALUES (3, 'Dark Souls 3', '2016-03-12');

INSERT INTO games (game_name, release_date)
VALUES ('Dark Souls 3', '2016-03-12');

SELECT * FROM games;

CREATE TABLE games(
    id INTEGER UNIQUE,
    game_name VARCHAR(50),
    release_date DATE
);

CREATE TABLE games(
    id INTEGER PRIMARY KEY,
    game_name VARCHAR(50) PRIMARY KEY,
    release_date DATE PRIMARY KEY
);

DROP TABLE games;


-- IDENTITY
CREATE TABLE transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12, 2),
    transaction_date TIMESTAMP DEFAULT NOW()
);

DROP TABLE transactions;

INSERT INTO transactions (amount)
VALUES (1567.23);

SELECT * FROM transactions;

INSERT INTO transactions (id, amount)
VALUES (30, 1567.23);

CREATE TABLE transactions (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12, 2),
    transaction_date TIMESTAMP DEFAULT NOW()
);

INSERT INTO transactions (amount)
VALUES (1567.23);

SELECT * FROM transactions;

INSERT INTO transactions (id, amount)
VALUES (30, 1567.23);

ALTER TABLE transactions
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE transactions
ALTER COLUMN id RESTART WITH 250;

INSERT INTO transactions (amount)
VALUES (1567.23);

SELECT * FROM transactions;









-- FOREIGN KEY
DROP TABLE courses;

CREATE TABLE teachers(
    id INTEGER PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50)
);

CREATE TABLE courses (
    id BIGINT PRIMARY KEY,
    course_name VARCHAR(150),
    price INTEGER DEFAULT 1500,
    teacher_id INTEGER REFERENCES teachers(id)
);

INSERT INTO teachers VALUES
(1, 'Davit', 'Maisuradze'),
(2, 'Giorgi', 'Giorgadze');

SELECT * FROM teachers;

INSERT INTO courses VALUES
(1, 'Java 1', 1789, 1),
(2, 'Java 2', 1919, 1),
(3, 'Python 1', 1231, 2);

SELECT * FROM courses;

INSERT INTO courses VALUES
(4, 'Python 2', 7283, 99); -- ეს არის პრობლემა


CREATE TABLE courses (
    id BIGINT PRIMARY KEY,
    course_name VARCHAR(150),
    price INTEGER 1500,
    teacher_id INTEGER,

    CONSTRAINT fk_teacher_id
        FOREIGN KEY (teacher_id)
        REFERENCES teachers(id)
);


-- JOIN
SELECT
    courses.course_name,
    teachers.first_name,
    teachers.last_name
FROM courses
JOIN teachers
    ON (courses.teacher_id = teachers.id);


SELECT *
FROM courses
JOIN teachers
    ON (courses.teacher_id = teachers.id);


SELECT
    c.course_name,
    t.first_name,
    t.last_name
FROM courses c
JOIN teachers t
    ON (c.teacher_id = t.id);